# Generated by Django 4.2.5 on 2023-09-19 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('valid_from', models.DateTimeField(verbose_name='действителен с')),
                ('valid_to', models.DateTimeField(verbose_name='действителен до')),
                ('discount', models.IntegerField(help_text='Проценты, от 0 до 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(verbose_name='активен')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
    ]
